//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.225
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Regex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Regex() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.Regex", typeof(Regex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (?&lt;target&gt;.+)[이가] (?&lt;skill&gt;.+) 추가 효과의 효과로 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 받았습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddDamageRegex {
            get {
                return ResourceManager.GetString("AddDamageRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \[charname:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;pet&gt;.+)[이가] 명령: (?&lt;skill&gt;.+)[을를] 사용해 (?&lt;target&gt;.+)에게 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 줬습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommandRegex {
            get {
                return ResourceManager.GetString("CommandRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;pet&gt;.+)의 소환이 해제됐습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSummonedOffRegex {
            get {
                return ResourceManager.GetString("CommonSummonedOffRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (((?&lt;name&gt;.+)[이가] )?소환: |((?&lt;name&gt;.+)[이가] )?)(?&lt;skill&gt;.+)[을를] 사용해 (?&lt;pet&gt;.+)[을를] 소환했습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSummonedRegex {
            get {
                return ResourceManager.GetString("CommonSummonedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;pet&gt;.+)[이가] 소환: (?&lt;skill&gt;.+) 효과를 사용해 (?&lt;target&gt;.+)에게 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 줬습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommonSummonedSumAtk {
            get {
                return ResourceManager.GetString("CommonSummonedSumAtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (치명타! )?(?&lt;target&gt;.+)[이가] (?&lt;skill&gt;.+)의 효과로 (?&lt;damage&gt;[^a-zA-Z]+)의 (중독 )?대미지를 받았습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContinuousDamage {
            get {
                return ResourceManager.GetString("ContinuousDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (치명타! )?((?&lt;name&gt;.+)[이가] )?(?&lt;skill&gt;.+)[을를] 사용해 (?&lt;target&gt;.+)([이가] 중독 상태가 됐습니다|에게 지속적인 대미지([을를]| 효과를) 줬습니다)\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContinuousRegex {
            get {
                return ResourceManager.GetString("ContinuousRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ((?&lt;name&gt;.+)[이가] )?(?&lt;skill&gt;.+)[을를] (사용합니다|사용해 (?&lt;target&gt;.+)[이가] 지연 폭발 효과를 받았습니다)\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedRegex {
            get {
                return ResourceManager.GetString("DelayedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Effect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Effect {
            get {
                return ResourceManager.GetString("Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (치명타 !)?(?&lt;target&gt;.+)[이가] (?&lt;effect&gt;.+) 효과의 효과로 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 받았습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EffectDamageRegex {
            get {
                return ResourceManager.GetString("EffectDamageRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ((?&lt;name&gt;.+)[이가] )?(?&lt;effect&gt;.+)[을를] 사용해 (효과가 발생됐습니다|자신에게 영향을 줬습니다)\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EffectRegex {
            get {
                return ResourceManager.GetString("EffectRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ((?&lt;name&gt;.+)[이가] )?소환: (?&lt;skill&gt;.+)을 사용해 (?&lt;target&gt;.+)[을를] 공격할 (?&lt;pet&gt;.+)[을를] 소환했습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnergySummonedRegex {
            get {
                return ResourceManager.GetString("EnergySummonedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;target&gt;.+)[이가] 마법(?&lt;effect&gt;.+) 피해 효과의 효과로 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 받았습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GodStoneAttrDamageRegex {
            get {
                return ResourceManager.GetString("GodStoneAttrDamageRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;target&gt;.+)[이가] 중독의 효과로 (?&lt;damage&gt;[^a-zA-Z]+)의 중독 대미지를 받았습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GodStonePoisonRegex {
            get {
                return ResourceManager.GetString("GodStonePoisonRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (치명타! )?((?&lt;name&gt;.+)[이가] )?(?&lt;target&gt;.+)에게 (?&lt;damage&gt;[^a-zA-Z]+)의 (|치명적인 )대미지를 줬습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InflictedRegex {
            get {
                return ResourceManager.GetString("InflictedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (치명타! )?((?&lt;name&gt;.+)[이가] )?(?&lt;skill&gt;.+)[을를] 사용해 ((?&lt;target&gt;.+)에게 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 줬습니다|(?&lt;target&gt;.+)에게 (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 주고 (?&lt;effect&gt;.+) 효과가 발생됐습니다|(?&lt;target&gt;.+)[이가] (?&lt;damage&gt;[^a-zA-Z]+)의 대미지를 (받고|입고) 일부 강화 마법이 제거됐습니다)\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InflictedSkillRegex {
            get {
                return ResourceManager.GetString("InflictedSkillRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;name&gt;.+) 님이 파티에 참가했습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JoinedGroupRegex {
            get {
                return ResourceManager.GetString("JoinedGroupRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;name&gt;.+) has been kicked out of your group\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KickedFromGroupRegex {
            get {
                return ResourceManager.GetString("KickedFromGroupRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;name&gt;.+) 님이 파티를 떠났습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LeftGroupRegex {
            get {
                return ResourceManager.GetString("LeftGroupRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;time&gt;[^a-zA-Z]+) : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimestampRegex {
            get {
                return ResourceManager.GetString("TimestampRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;kinah&gt;[^a-zA-Z]+)키나를 얻었습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YouEarnedKinahRegex {
            get {
                return ResourceManager.GetString("YouEarnedKinahRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;ap&gt;[^a-zA-Z]+) 어비스 포인트를 얻었습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YouGainedApRegex {
            get {
                return ResourceManager.GetString("YouGainedApRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;target&gt;.+)에게 (?&lt;exp&gt;[^a-zA-Z]+)만큼의 경험치를 얻었습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YouGainedExpRegex {
            get {
                return ResourceManager.GetString("YouGainedExpRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (?&lt;kinah&gt;[^a-zA-Z]+)키나를 사용했습니다\.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string YouSpentKinahRegex {
            get {
                return ResourceManager.GetString("YouSpentKinahRegex", resourceCulture);
            }
        }
    }
}
