//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.ClassList", typeof(ClassList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 살성.
        /// </summary>
        internal static string 살성 {
            get {
                return ResourceManager.GetString("살성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 호법성.
        /// </summary>
        internal static string 호법성 {
            get {
                return ResourceManager.GetString("호법성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 치유성.
        /// </summary>
        internal static string 치유성 {
            get {
                return ResourceManager.GetString("치유성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검성.
        /// </summary>
        internal static string 검성 {
            get {
                return ResourceManager.GetString("검성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 궁성.
        /// </summary>
        internal static string 궁성 {
            get {
                return ResourceManager.GetString("궁성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마도성.
        /// </summary>
        internal static string 마도성 {
            get {
                return ResourceManager.GetString("마도성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정령성.
        /// </summary>
        internal static string 정령성 {
            get {
                return ResourceManager.GetString("정령성", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수호성.
        /// </summary>
        internal static string 수호성 {
            get {
                return ResourceManager.GetString("수호성", resourceCulture);
            }
        }
    }
}
