//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlayerControlRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayerControlRes() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.PlayerControlRes", typeof(PlayerControlRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   리스트 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClearListMenuHeader {
            get {
                return ResourceManager.GetString("ClearListMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포스 채팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyMacroAllianceMenuHeader {
            get {
                return ResourceManager.GetString("CopyMacroAllianceMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파티 채팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyMacroGroupMenuHeader {
            get {
                return ResourceManager.GetString("CopyMacroGroupMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레기온 채팅과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyMacroLegionMenuHeader {
            get {
                return ResourceManager.GetString("CopyMacroLegionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사 매크로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyMacroMenuHeader {
            get {
                return ResourceManager.GetString("CopyMacroMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyMenuHeader {
            get {
                return ResourceManager.GetString("CopyMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   친구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FriendMenuHeader {
            get {
                return ResourceManager.GetString("FriendMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파티원과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupMemeberMenuHeader {
            get {
                return ResourceManager.GetString("GroupMemeberMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IgnorePlayerMenuHeader {
            get {
                return ResourceManager.GetString("IgnorePlayerMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveMenuHeader {
            get {
                return ResourceManager.GetString("RemoveMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DPS등 전부 리셋과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetCountsMenuHeader {
            get {
                return ResourceManager.GetString("ResetCountsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용한 스킬들...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ViewSkillsMenuHeader {
            get {
                return ResourceManager.GetString("ViewSkillsMenuHeader", resourceCulture);
            }
        }
    }
}
