//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.225
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingsDamageMeter.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowMainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowMainRes() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingsDamageMeter.Localization.WindowMainRes", typeof(WindowMainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   이 프로그램은...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AboutMenuHeader {
            get {
                return ResourceManager.GetString("AboutMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파티원 추가...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddByNameMenuHeader {
            get {
                return ResourceManager.GetString("AddByNameMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이온 웹사이트 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AionWebPage {
            get {
                return ResourceManager.GetString("AionWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어비스 포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApMainViewMenuHeader {
            get {
                return ResourceManager.GetString("ApMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chatlog 해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChatlogSetup {
            get {
                return ResourceManager.GetString("ChatlogSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseBtnToolTip {
            get {
                return ResourceManager.GetString("CloseBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfirmCloseCaption {
            get {
                return ResourceManager.GetString("ConfirmCloseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말로 종료 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfirmCloseMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DamageMainViewMenuHeader {
            get {
                return ResourceManager.GetString("DamageMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dps과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DpsMainViewMenuHeader {
            get {
                return ResourceManager.GetString("DpsMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경험치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExperienceMainViewMenuHeader {
            get {
                return ResourceManager.GetString("ExperienceMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간당 경험치:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExpPerHourToolTip {
            get {
                return ResourceManager.GetString("ExpPerHourToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   신석대미지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GodStoneMainViewMenuHeader {
            get {
                return ResourceManager.GetString("GodStoneMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파티원의 정보만과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupOnlyMenuHeader {
            get {
                return ResourceManager.GetString("GroupOnlyMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내 정보만과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideOthersMenuHeader {
            get {
                return ResourceManager.GetString("HideOthersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무시할 대상자 리스트...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IgnoreListMenuHeader {
            get {
                return ResourceManager.GetString("IgnoreListMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   얻음:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KinahEarnedToolTip {
            get {
                return ResourceManager.GetString("KinahEarnedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키나과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KinahMainViewMenuHeader {
            get {
                return ResourceManager.GetString("KinahMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string KinahSpentToolTip {
            get {
                return ResourceManager.GetString("KinahSpentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LanguageMenuHeader {
            get {
                return ResourceManager.GetString("LanguageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chat.log 위치 지정...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LocateLogMenuHeader {
            get {
                return ResourceManager.GetString("LocateLogMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogLanguageMenuHeader {
            get {
                return ResourceManager.GetString("LogLanguageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보여질 항목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainViewMenuHeader {
            get {
                return ResourceManager.GetString("MainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MinimizeBtnToolTip {
            get {
                return ResourceManager.GetString("MinimizeBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 존재하는 유저 이름입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NameTakenMessage {
            get {
                return ResourceManager.GetString("NameTakenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   투명도 조절과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpacitySliderToolTip {
            get {
                return ResourceManager.GetString("OpacitySliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   chat.log를 열 수 없습니다. 사용 설명서를 보시고 chat.log를 생성하시고 설정해 주세요. &quot;{0} -&gt; {1}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenLogError {
            get {
                return ResourceManager.GetString("OpenLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OptionsBtnToolTip {
            get {
                return ResourceManager.GetString("OptionsBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   퍼센트(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PercentMainViewMenuHeader {
            get {
                return ResourceManager.GetString("PercentMainViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지 측정 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PowerOffBtnTooltip {
            get {
                return ResourceManager.GetString("PowerOffBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지 측정 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PowerOnBtnTooltip {
            get {
                return ResourceManager.GetString("PowerOnBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크기조절과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResizeThumbToolTip {
            get {
                return ResourceManager.GetString("ResizeThumbToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내 이름 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetYouAliasMenuHeader {
            get {
                return ResourceManager.GetString("SetYouAliasMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대미지순과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByDamageMenuHeader {
            get {
                return ResourceManager.GetString("SortByDamageMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DPS순과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByDpsMenuHeader {
            get {
                return ResourceManager.GetString("SortByDpsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름순과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByNameMenuHeader {
            get {
                return ResourceManager.GetString("SortByNameMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   순서 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortingMenuHeader {
            get {
                return ResourceManager.GetString("SortingMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항상 위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TopMostCheckBoxToolTip {
            get {
                return ResourceManager.GetString("TopMostCheckBoxToolTip", resourceCulture);
            }
        }
    }
}
